on:
  push:
    branches: [main]
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

name: Web Build
jobs:
  checkout:
    name: Checkout Code
    runs-on: web-self-hosted
    steps:
      - uses: actions/checkout@v4

  install_dependencies_and_build:
    name: Install Dependencies and Build Web
    runs-on: web-self-hosted
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - run: cd /home/neko/Workspace/Git/imnyang/imnyang
      - run: git pull
      - run: bun install
      - run: bun run build
      - run: pm2 restart imnya.ng > /dev/null 2>&1

  replace:
    name: Replace Old Build with New Build
    runs-on: web-self-hosted
    needs: install_dependencies_and_build
    steps:
      - run: rm -rf /var/static/imnya.ng && cp -r dist /var/static/imnya.ng
