on:
  push:
    branches: [main]

name: Web Build
jobs: 
  build:
    name: Build the web
    runs-on: web-self-hosted
    steps:
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - run: rm -rf /var/static/imnya.ng
      - run: cp -r dist /var/static/imnya.ng
    
    
